ZJUSE/ZJUSE/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from machina.app import board

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('display.urls')),
    url(r'^forum/', include('discuss.urls')),
]

ZJUSE/display/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.log_in, name='login'),
    url(r'^logout/$', views.log_out, name='logout'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^set_password_question/$', views.set_password_question, name='set_password_question'),
    url(r'^change_password_using_question/$', views.change_password_using_question, name='change_password_using_question'),

    url(r'^add_student_to_system/$', views.add_student_to_system, name='add_student_to_system'),
    url(r'^add_student_to_class/$', views.add_student_to_class, name='add_student_to_class'),

    url(r'^course/(?P<course_id>[0-9]+)/$', views.course_detail, name='course_detail'),
    url(r'^course/(?P<course_id>[0-9]+)/modify/$', views.modify_course, name='modify_course'),
    url(r'^resource/(?P<resource_id>[0-9]+)/$', views.resource_detail, name='resource_detail'),
    url(r'^course/(?P<course_id>[0-9]+)/resource/add/$', views.add_resource, name='add_resource'),
    url(r'^resource/(?P<resource_id>[0-9]+)/modify/$', views.modify_resource, name='modify_resource'),
    url(r'^resource/(?P<resource_id>[0-9]+)/delete/$', views.delete_resource, name='delete_resource'),

    url(r'^teacher_description/(?P<teacher_id>[0-9]+)/$', views.teacher_description, name='teacher_description'),

    url(r'^article/(?P<article_id>[0-9]+)/$', views.article_detail, name='article_detail'),
    url(r'^article/add/$', views.add_article, name='add_article'),
    url(r'^article/(?P<article_id>[0-9]+)/modify/$', views.modify_article, name='modify_article'),
    url(r'^article/(?P<article_id>[0-9]+)/delete/$', views.delete_article, name='delete_article'),

    url(r'^notification/(?P<notification_id>[0-9]+)/$', views.notification_detail, name='notification_detail'),
    url(r'^notification/add/$', views.add_notification, name='add_notification'),
    url(r'^notification/(?P<notification_id>[0-9]+)/modify/$', views.modify_notification, name='modify_notification'),
    url(r'^notification/(?P<notification_id>[0-9]+)/delete/$', views.delete_notification, name='delete_notification'),


    url(r'modify_teacher_description/$', views.modify_teacher_description, name='modify_teacher_description'),

    url(r'^teacher/$', views.teacher_index, name='teacher_index'),
    url(r'^teacher/class/(?P<class_id>[0-9]+)/$', views.teacher_my_class, name='teacher_class'),
    url(r'^teacher/homework/(?P<homework_id>[0-9]+)/$', views.teacher_check_homework, name='teacher_check_homework'),
    url(r'^teacher/homework/add/$', views.add_homework, name='add_homework'),
    url(r'^teacher/homework/(?P<homework_id>[0-9]+)/modify/$', views.modify_homework, name='modify_homework'),
    url(r'^teacher/homework/(?P<homework_id>[0-9]+)/delete/$', views.delete_homework, name='delete_homework'),
    url(r'^teacher/homework/check/(?P<finish_id>[0-9]+)/$', views.teacher_check_detail, name='teacher_check_detail'),

    url(r'^student/$', views.student_index, name='student_index'),
    url(r'^student/class/(?P<class_id>[0-9]+)/$', views.student_my_class, name='student_class'),
    url(r'^student/homework/(?P<homework_id>[0-9]+)/$', views.student_view_homework, name='student_view_homework'),
    url(r'^student/homework/upload/(?P<finish_id>[0-9]+)/$', views.student_upload_homework, name='student_upload_homework'),

    url(r'^guest/$', views.guest_index, name='guest_index'),

    url(r'^teacher/course_list/$', views.teacher_course_list, name='teacher_course_list'),
    url(r'^student/course_list/$', views.student_course_list, name='student_course_list'),
    url(r'^guest/course_list/$', views.guest_course_list, name='guest_course_list'),

    url(r'^teacher/teacher_list/$', views.teacher_teacher_list, name='teacher_teacher_list'),
    url(r'^student/teacher_list/$', views.student_teacher_list, name='student_teacher_list'),
    url(r'^guest/teacher_list/$', views.guest_teacher_list, name='guest_teacher_list'),

    url(r'^teacher_notification_list/$', views.teacher_notification_list, name='teacher_notification_list'),
    url(r'^student_notification_list/$', views.student_notification_list, name='student_notification_list'),

    url(r'^teacher_homework_list/$', views.teacher_homework_list, name='teacher_homework_list'),
    url(r'^student_homework_list/$', views.student_homework_list, name='student_homework_list'),

    url(r'^teacher_article_list/$', views.teacher_article_list, name='teacher_article_list'),
    url(r'^student_article_list/$', views.student_article_list, name='student_article_list'),
    url(r'^guest_article_list/$', views.guest_article_list, name='guest_article_list'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ZJUSE/display/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class PasswordQuestion(models.Model):
    question = models.CharField(max_length=50)
    def __str__(self):
        return self.question

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    school_id = models.CharField(max_length=20)
    question = models.ForeignKey(PasswordQuestion, on_delete=models.CASCADE, blank=True, null=True)
    answer = models.CharField(max_length=50)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.school_id = instance.username
    instance.profile.save()


class Teacher(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    experience = models.TextField(blank=True)
    research = models.TextField(blank=True)
    style = models.TextField(blank=True)
    publication = models.TextField(blank=True)
    honor = models.TextField(blank=True)
    contact = models.TextField(blank=True)
    other = models.TextField(blank=True)
    def __str__(self):
        return self.name

class Student(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name

class Course(models.Model):
    name = models.CharField(max_length=50)
    plan = models.TextField(blank=True)
    book = models.TextField(blank=True)
    background = models.TextField(blank=True)
    exam = models.TextField(blank=True)
    knowledge = models.TextField(blank=True)
    project = models.TextField(blank=True)
    def __str__(self):
        return self.name

class Class(models.Model):
    name = models.CharField(max_length=20)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    time = models.TextField(blank=True)
    def __str__(self):
        return self.name

class Teaches(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    clazz = models.ForeignKey(Class, on_delete=models.CASCADE)
    def __str__(self):
        return self.teacher.name + ' ' + self.clazz.name

class Join(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    clazz = models.ForeignKey(Class, on_delete=models.CASCADE)
    def __str__(self):
        return self.student.name + ' ' + self.clazz.name

class Article(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = models.TextField()
    attached_file = models.FileField(upload_to='article_file/', blank=True)
    pub_date = models.DateTimeField()
    def __str__(self):
        return self.title

class Notification(models.Model):
    clazz = models.ForeignKey(Class, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = models.TextField()
    pub_date = models.DateTimeField()
    publisher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    def __str__(self):
        return self.title

class Resource(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=100, blank=True)
    attached_file = models.FileField(upload_to='resource/')
    simple_file = models.FileField(upload_to='resource/', blank=True)
    pub_date = models.DateTimeField()
    uploader = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    def __str__(self):
        return self.title

class Link(models.Model):
    name = models.CharField(max_length=20)
    address = models.URLField()
    def __str__(self):
        return self.name

class Homework(models.Model):
    clazz = models.ForeignKey(Class, on_delete=models.CASCADE)
    title = models.CharField(max_length=20)
    content = models.TextField()
    attached_file = models.FileField(upload_to='resource/homework/', blank=True)
    pub_date = models.DateTimeField()
    weight = models.IntegerField()
    ddl = models.DateTimeField()
    def __str__(self):
        return self.title

class Finish(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    homework = models.ForeignKey(Homework, on_delete=models.CASCADE)
    upload_time = models.DateTimeField(blank=True, null=True)
    upload_file = models.FileField(upload_to='homework/', blank=True)
    score = models.IntegerField(default=0)
    evaluation = models.TextField(blank=True)
    checked = models.BooleanField(default=True)
    def __str__(self):
        return self.student.name + ' ' + self.homework.title

ZJUSE/display/forms.py
from django import forms
from .models import *
from .utils import TimeSelectorWidget
from datetime import datetime

class DeleteForm(forms.Form):
    confirm = forms.CharField(widget=forms.HiddenInput())

class NamePass(forms.Form):
    username = forms.CharField(label="用户名")
    password = forms.CharField(label="密码", widget=forms.PasswordInput())

class ChangePass(forms.Form):
    old_passwd = forms.CharField(label="原密码", widget=forms.PasswordInput())
    new_passwd_1 = forms.CharField(label="新密码", widget=forms.PasswordInput())
    new_passwd_2 = forms.CharField(label="确认密码", widget=forms.PasswordInput())

class PasswordQuestionForm(forms.Form):
    question = forms.ModelChoiceField(label="密保问题", queryset=PasswordQuestion.objects.all())
    answer = forms.CharField(label="答案")

class ChangePassUsingQuestion(forms.Form):
    question = forms.ModelChoiceField(label="密保问题", queryset=PasswordQuestion.objects.all())
    answer = forms.CharField(label="答案")
    new_passwd_1 = forms.CharField(label="新密码", widget=forms.PasswordInput())
    new_passwd_2 = forms.CharField(label="确认密码", widget=forms.PasswordInput())

class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        exclude = ['user']
        labels = {
                'name': '姓名', 'experience': '教学经验', 'research': '研究成果', 'style': '教学风格',
                'publication': '出版作品', 'honor': '所获荣誉', 'contact': '联系方式', 'other': '备注',
                }
        widgets = {
                'name': forms.TextInput(attrs={'class': 'form-control'}),
                'experience': forms.Textarea(attrs={'class': 'form-control'}),
                'research': forms.Textarea(attrs={'class': 'form-control'}),
                'style': forms.Textarea(attrs={'class': 'form-control'}),
                'publication': forms.Textarea(attrs={'class': 'form-control'}),
                'honor': forms.Textarea(attrs={'class': 'form-control'}),
                'contact': forms.Textarea(attrs={'class': 'form-control'}),
                'other': forms.Textarea(attrs={'class': 'form-control'}),
                }

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        exclude = []
        labels = {
                'name': '课程名称', 'plan': '教学计划', 'book': '教材', 'background': '国际国内背景',
                'exam': '考核方式', 'knowledge': '前置知识', 'project': '大作业',
                }
        widgets = {
                'name': forms.TextInput(attrs={'class': 'form-control'}),
                'plan': forms.Textarea(attrs={'class': 'form-control'}),
                'book': forms.Textarea(attrs={'class': 'form-control'}),
                'background': forms.Textarea(attrs={'class': 'form-control'}),
                'exam': forms.Textarea(attrs={'class': 'form-control'}),
                'knowledge': forms.Textarea(attrs={'class': 'form-control'}),
                'project': forms.Textarea(attrs={'class': 'form-control'}),
                }

class NotificationForm(forms.Form):
    course = forms.ModelChoiceField(label="课程", queryset=Course.objects.all(), required=False)
    clazz = forms.ModelChoiceField(label="班级", queryset=Class.objects.all())
    title = forms.CharField(label="标题", max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}))
    content = forms.CharField(label="内容", widget=forms.Textarea(attrs={'class': 'form-control'}))

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['teacher', 'title', 'content', 'attached_file', 'pub_date']
        widgets = {'teacher': forms.HiddenInput(),
                'pub_date': forms.HiddenInput(),
                'title': forms.TextInput(attrs={'class': 'form-control'}),
                'content': forms.Textarea(attrs={'class': 'form-control'}),
                }
        labels = {
                'title':'标题',
                'content':'内容',
                'attached_file':'附件',
                }

class ResourceForm(forms.ModelForm):
    class Meta:
        model = Resource
        exclude = []
        widgets = {
                'course': forms.HiddenInput(),
                'pub_date': forms.HiddenInput(),
                'uploader': forms.HiddenInput(),
                'title': forms.TextInput(attrs={'class': 'form-control'}),
                'description': forms.TextInput(attrs={'class': 'form-control'}),
                }
        labels = {
                'title': '标题',
                'description': '简介',
                'attached_file': '文件',
                'simple_file': '简化文件',
                }
    def __init__(self, *args, **kwargs):
        required = True
        try:
            required = kwargs.pop('required')
        except:
            pass
        super(ResourceForm, self).__init__(*args, **kwargs)
        print(required)
        if required == False:
            self.fields['attached_file'].required = False

class HomeworkForm(forms.ModelForm):
    course = forms.ModelChoiceField(label="课程", queryset=Course.objects.all(), required=False)
    ddl_date = forms.DateField(widget=forms.SelectDateWidget)
    ddl_time = forms.TimeField(widget=TimeSelectorWidget())
    class Meta:
        model = Homework
        exclude = []
        widgets = {
                'pub_date': forms.HiddenInput(),
                'ddl': forms.HiddenInput(),
                'title': forms.TextInput(attrs={'class': 'form-control'}),
                'content': forms.Textarea(attrs={'class': 'form-control'}),
                'weight': forms.TextInput(attrs={'class': 'form-control'}),
                }
        labels = {
                'clazz': '班级',
                'title': '标题',
                'content': '内容',
                'attached_file': '附件',
                'weight': '权重',
                'ddl_date': '截止时间',
                'ddl_time': '',
                }
    def save(self, commit=True):
        return super(HomeworkForm, self).save(commit=commit)

    
class StudentUploadHomeworkForm(forms.ModelForm):
    class Meta:
        model = Finish
        exclude = ['score', 'evaluation', 'checked']
        widgets = {
                'student': forms.HiddenInput(),
                'homework': forms.HiddenInput(),
                'upload_time': forms.HiddenInput(),
                }

class TeacherCheckHomework(forms.ModelForm):
    class Meta:
        model = Finish
        exclude = ['student', 'homework', 'upload_time', 'upload_file', 'checked']

class AddStudentToSystemForm(forms.Form):
    namelist = forms.FileField()

class AddStudentToClassForm(forms.Form):
    clazz = forms.ModelChoiceField(label="班级", queryset=Class.objects.all())
    namelist = forms.FileField()

ZJUSE/display/templates/display/change_password.html
<!DOCTYPE html>
<html>
	<head>
        <meta charset="utf-8" />
		<title>修改密码</title>
	</head>
	<body>
        <form action="{% url 'change_password' %}" method="post">
            {% csrf_token %}
            <table>
            {{ form }}
            </table>
            <input type="submit" value="Submit" />
        </form>
	</body>
</html>

ZJUSE/display/templates/display/delete_article.html
<!DOCTYPE html>
<html>
	<head>
        <meta charset="utf-8" />
		<title>删除文章</title>
	</head>
	<body>
        确认删除？
        <form action="{% url 'delete_article' article.id %}" method="post">
            {% csrf_token %}
            <table>
            {{ form }}
            </table>
            <input type="submit" value="确认" />
        </form>
	</body>
</html>

ZJUSE/display/templates/display/delete_homework.html
<!DOCTYPE html>
<html>
	<head>
        <meta charset="utf-8" />
		<title>删除作业</title>
	</head>
	<body>
        确认删除？
        <form action="{% url 'delete_homework' homework.id %}" method="post">
            {% csrf_token %}
            <table>
            {{ form }}
            </table>
            <input type="submit" value="确认" />
        </form>
	</body>
</html>

ZJUSE/display/templates/display/student_article_list.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
	<meta charset="utf-8" />
    <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.ico' %}">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>文章列表</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Bootstrap core CSS     -->
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="{% static 'assets/css/animate.min.css' %}" rel="stylesheet"/>

    <!--  Light Bootstrap Table core CSS    -->
    <link href="{% static 'assets/css/light-bootstrap-dashboard.css' %}" rel="stylesheet"/>


    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="{% static 'assets/css/demo.css' %}" rel="stylesheet" />


    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="{% static 'assets/css/pe-icon-7-stroke.css' %}" rel="stylesheet" />

</head>
<body>

<div class="wrapper">
    <div class="sidebar" data-color="azure" data-image="{% static 'assets/img/sidebar-2.jpg' %}">

    <!--

        Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
        Tip 2: you can also add an image using data-image tag

    -->

    	<div class="sidebar-wrapper">
            <div class="logo">
                <a href="" class="simple-text">
                    ZJUSE
                </a>
            </div>

            <ul class="nav">
                <li>
                    <a href="{% url 'index' %}">
                        <i class="pe-7s-display2"></i>
                        <p>主页</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'student_notification_list' %}">
                        <i class="pe-7s-bell"></i>
                        <p>通知列表</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'student_homework_list' %}">
                        <i class="pe-7s-notebook"></i>
                        <p>作业列表</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'student_course_list' %}">
                        <i class="pe-7s-study"></i>
                        <p>课程列表</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'student_teacher_list' %}">
                        <i class="pe-7s-users"></i>
                        <p>教师列表</p>
                    </a>
                </li>
                <li class="active">
                    <a href="{% url 'student_article_list' %}">
                        <i class="pe-7s-news-paper"></i>
                        <p>文章列表</p>
                    </a>
                </li>
                <li>
                    <a href="/forum/">
                        <i class="pe-7s-chat"></i>
                        <p>教学论坛</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'change_password' %}">
                        <i class="pe-7s-tools"></i>
                        <p>账户设置</p>
                    </a>
                </li>
            </ul>
    	</div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#"></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-left">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-cog"></i>
								<p class="hidden-lg hidden-md">主题设置</p>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a onclick="changeColor('green')">草木绿</a></li>
                                <li><a onclick="changeColor('azure')">晴空蓝</a></li>
                                <li><a onclick="changeColor('orange')">秋日黄</a></li>
                                <li><a onclick="changeColor('blue')">湖水蓝</a></li>
                                <li><a onclick="changeColor('red')">枫叶红</a></li>
                                <li><a onclick="changeColor('purple')">晚霞紫</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-globe"></i>
                                    <b class="caret hidden-lg hidden-md"></b>
                              </a>
                              <ul class="dropdown-menu">
                                <li><a href="#">中文</a></li>
                                <li><a href="#">English</a></li>
                              </ul>
                        </li>
                        <li>
                           <a href="">
                                <i class="fa fa-search"></i>
								<p class="hidden-lg hidden-md">Search</p>
                            </a>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="">
                               <p>{{ student.name }}</p>
                            </a>

                        </li>
                        <li>
                            <a href="{% url 'logout' %}">
                                <p>注销</p>
                            </a>
                        </li>
						<li class="separator hidden-lg"></li>
                    </ul>
                </div>
            </div>
        </nav>


        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">

                            <div class="header">
                                <h4 class="title">文章列表</h4>
                            </div>
                            <div class="content">
                                <div class="content table-responsive table-full-width">
                                    <table class="table table-hover table-striped">
                                        <thead>
                                            <th>文章标题</th>
                                            <th>作者</th>
                                            <th>发布时间</th>
                                        </thead>
                                        <tbody>
                                        {% for article in article_set %}
                                            <tr>
                                                <td><a href="{% url 'article_detail' article.id %}" target="_blank">{{ article.title }}</a></td>
                                                <td><a href="{% url 'teacher_description' article.teacher.id %}" target="_blank">{{ article.teacher.name }}</a></td>
                                                <td>{{ article.pub_date }}</td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>

                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>


        <footer class="footer">
            <div class="container-fluid">
                <p class="copyright pull-right">
                    &copy; <script>document.write(new Date().getFullYear())</script> <a href="">ZJUSE GROUP 12</a>
                </p>
            </div>
        </footer>

    </div>
</div>


</body>

    <!--   Core JS Files   -->
    <script src="{% static 'assets/js/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}" type="text/javascript"></script>

	<!--  Charts Plugin -->
    <script src="{% static 'assets/js/chartist.min.js' %}"></script>

    <!--  Notifications Plugin    -->
    <script src="{% static 'assets/js/bootstrap-notify.js' %}"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
    <script src="{% static 'assets/js/light-bootstrap-dashboard.js' %}"></script>

	<!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
    <script src="{% static 'assets/js/demo.js' %}"></script>

	<script type="text/javascript">
    	$(document).ready(function(){


    	});
	</script>
    <script>
        function changeColor(color){
            document.getElementsByClassName('sidebar')[0].setAttribute('data-color', color);
        }
    </script>

</html>

ZJUSE/display/templates/display/teacher_list.html
<!DOCTYPE html>
<html>
	<head>
        <meta charset="utf-8" />
		<title>教师列表</title>
	</head>
	<body>
        <h1>教师列表</h1>
        <ul>
            {% for teacher in teacher_set %}
            <li><a href="{% url 'teacher_description' teacher.id %}">{{ teacher.name }}</a></li>
            {% endfor %}
        </ul>
	</body>
</html>